// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPTTest;

#nullable disable

namespace TPTTest.Migrations
{
    [DbContext(typeof(APPDBContext))]
    [Migration("20240217232951_TPTtest")]
    partial class TPTtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPTTest.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TPTTest.Models.Customer", b =>
                {
                    b.HasBaseType("TPTTest.Models.Person");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TPTTest.Models.Employee", b =>
                {
                    b.HasBaseType("TPTTest.Models.Person");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TPTTest.Models.Manager", b =>
                {
                    b.HasBaseType("TPTTest.Models.Person");

                    b.Property<int>("VIPNumer")
                        .HasColumnType("int");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("TPTTest.Models.Customer", b =>
                {
                    b.HasOne("TPTTest.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("TPTTest.Models.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPTTest.Models.Employee", b =>
                {
                    b.HasOne("TPTTest.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("TPTTest.Models.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPTTest.Models.Manager", b =>
                {
                    b.HasOne("TPTTest.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("TPTTest.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
